server.port: 7007
daisuke:
  server-type: SonarQube
  analysis-server: 
    url: http://codereview.edison.it/sonarqube
    token: e65a3a0ab2e015a069765ea6553f54925ae4d374
  output:
    path: D:/temp/report.csv
spring:
  data:
    jpa:
      repositories:
        bootstrap-mode: default
        enabled: true
  jpa:
    database: sql-server
    generate-ddl: false
    show-sql: true
    hibernate:
      use-new-id-generator-mappings: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    name: myDatasource
    url: jdbc:sqlserver://10.202.110.101;databaseName=CodeQualityGovernance;user=tibcospotfire;password=Edison2019
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
logging:
  level:
    org.springframework: INFO
    org.springframework.web.filter.CommonsRequestLoggingFilter: INFO
    com.daisuke: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file:
    name: ./logs/springboot-daisuke.log
    max-size:
      10MB
   
    